# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Use `just pre-commit-update` to update to the latest versions of the hooks

# Install hooks for the pre-commit and pre-push stages by default
default_install_hook_types: [pre-commit, pre-push]

# Exclude VSCode settings directory
exclude: ^(.vscode/).*

# Define the hooks to run
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--allow-multiple-documents', '--unsafe']
    # Exclude Helm chart templates from YAML checks, as they are Go templates, not pure YAML
    exclude: templates/.*
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/biomejs/pre-commit
  rev: v2.2.6 # Use the sha / tag you want to point at
  hooks:
    - id: biome-check
